<?php

namespace BookBundle\Repository;

/**
 * SubjectToGradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectToGradeRepository extends \Doctrine\ORM\EntityRepository
{
}
